services:
  untitled-project-dwh:
    image: postgres:latest
    container_name: untitled-project-dwh
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DWH_POSTGRES_DB}
      - POSTGRES_USEfR=${DWH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DWH_POSTGRES_PASSWORD}
    ports:
      - ${DWH_POSTGRES_PORT}:5432
    networks:
      - airflow-untitled-project-net
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - untitled-project-dwh-vol:/var/lib/postgresql/data


networks:
  airflow-untitled-project-net:
    external: true
    name: airflow-untitled-project-net

volumes:
  untitled-project-dwh-vol:
    driver: local
    name: untitled-project-dwh-vol